# Generated by Django 4.0.3 on 2022-04-06 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nom')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nom')),
                ('price', models.FloatField(verbose_name='prix')),
                ('image', models.ImageField(upload_to='media/', verbose_name='couvertur')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_apps.category')),
            ],
        ),
    ]
