# Generated by Django 4.0.3 on 2022-04-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_apps', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='devise',
            field=models.CharField(choices=[('USD', 'dollars'), ('CDF', 'franc')], default=None, max_length=10, verbose_name='devise'),
            preserve_default=False,
        ),
    ]
